import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./components/Welcomepage/Footer";
import Foot from "./components/Welcomepage/Foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 w-full bg-white z-50">
          <Header />
        </div>
        {children}
        <div className="bg-gray-50">
          <Footer />
          <Foot />
        </div>
      </body>
    </html>
  );
}
